//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRR.Core.Domain
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/HRR.Core.Domain")]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccountIDField;
        
        private string AvatarPathField;
        
        private System.DateTime BirthdateField;
        
        private int ChangedByField;
        
        private System.DateTime DateCreatedField;
        
        private int DepartmentIDField;
        
        private HRR.Core.Domain.Department DepartmentRefField;
        
        private string EmailField;
        
        private int EnteredByField;
        
        private string FacebookPathField;
        
        private string FirstNameField;
        
        private System.DateTime HireDateField;
        
        private int IDField;
        
        private bool IsActiveField;
        
        private bool IsManagerField;
        
        private string LastNameField;
        
        private System.DateTime LastUpdatedField;
        
        private string LinkedInPathField;
        
        private HRR.Core.Domain.Person ManagerField;
        
        private int ManagerIDField;
        
        private bool MarkedForDeletionField;
        
        private string NameField;
        
        private string PasswordField;
        
        private string PasswordAnswerField;
        
        private string PasswordQuestionField;
        
        private int RoleIDField;
        
        private HRR.Core.Domain.Person[] TeammatesField;
        
        private System.Nullable<System.DateTime> TerminationDateField;
        
        private string TitleField;
        
        private string TwitterPathField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarPath
        {
            get
            {
                return this.AvatarPathField;
            }
            set
            {
                this.AvatarPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate
        {
            get
            {
                return this.BirthdateField;
            }
            set
            {
                this.BirthdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChangedBy
        {
            get
            {
                return this.ChangedByField;
            }
            set
            {
                this.ChangedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated
        {
            get
            {
                return this.DateCreatedField;
            }
            set
            {
                this.DateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRR.Core.Domain.Department DepartmentRef
        {
            get
            {
                return this.DepartmentRefField;
            }
            set
            {
                this.DepartmentRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EnteredBy
        {
            get
            {
                return this.EnteredByField;
            }
            set
            {
                this.EnteredByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookPath
        {
            get
            {
                return this.FacebookPathField;
            }
            set
            {
                this.FacebookPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HireDate
        {
            get
            {
                return this.HireDateField;
            }
            set
            {
                this.HireDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManager
        {
            get
            {
                return this.IsManagerField;
            }
            set
            {
                this.IsManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkedInPath
        {
            get
            {
                return this.LinkedInPathField;
            }
            set
            {
                this.LinkedInPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRR.Core.Domain.Person Manager
        {
            get
            {
                return this.ManagerField;
            }
            set
            {
                this.ManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerID
        {
            get
            {
                return this.ManagerIDField;
            }
            set
            {
                this.ManagerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MarkedForDeletion
        {
            get
            {
                return this.MarkedForDeletionField;
            }
            set
            {
                this.MarkedForDeletionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordAnswer
        {
            get
            {
                return this.PasswordAnswerField;
            }
            set
            {
                this.PasswordAnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordQuestion
        {
            get
            {
                return this.PasswordQuestionField;
            }
            set
            {
                this.PasswordQuestionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRR.Core.Domain.Person[] Teammates
        {
            get
            {
                return this.TeammatesField;
            }
            set
            {
                this.TeammatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TerminationDate
        {
            get
            {
                return this.TerminationDateField;
            }
            set
            {
                this.TerminationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwitterPath
        {
            get
            {
                return this.TwitterPathField;
            }
            set
            {
                this.TwitterPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/HRR.Core.Domain")]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string NameField;
        
        private HRR.Core.Domain.Person[] PeopleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRR.Core.Domain.Person[] People
        {
            get
            {
                return this.PeopleField;
            }
            set
            {
                this.PeopleField = value;
            }
        }
    }
}
namespace HRR.WCFServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/HRR.WCFServices")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IComments")]
public interface IComments
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComments/GetData", ReplyAction="http://tempuri.org/IComments/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComments/GetCommentListByFilters", ReplyAction="http://tempuri.org/IComments/GetCommentListByFiltersResponse")]
    string GetCommentListByFilters(HRR.Core.Domain.Person[] teammates, System.Nullable<int> userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComments/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IComments/GetDataUsingDataContractResponse")]
    HRR.WCFServices.CompositeType GetDataUsingDataContract(HRR.WCFServices.CompositeType composite);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICommentsChannel : IComments, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CommentsClient : System.ServiceModel.ClientBase<IComments>, IComments
{
    
    public CommentsClient()
    {
    }
    
    public CommentsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CommentsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CommentsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CommentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public string GetCommentListByFilters(HRR.Core.Domain.Person[] teammates, System.Nullable<int> userID)
    {
        return base.Channel.GetCommentListByFilters(teammates, userID);
    }
    
    public HRR.WCFServices.CompositeType GetDataUsingDataContract(HRR.WCFServices.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
}
